import re
import yitizi
import pinyin

# Converts charlist.csv (credit to https://words.hk/faiman/analysis/charlist/) to a 2D string array literal 
# in jyutping.h, so that the pronunciations are directly compiled into the executable

class Honzi:
    def __init__(self, char, jyutpings, pinyin):
            self.char = char
            jyutpings = [(jyutping[0], int(jyutping[1])) for jyutping in jyutpings] # convert 'commanality' score to int so it can be sorted
            self.jyutpings = jyutpings
            self.jyutpings.sort(key=lambda x: x[1], reverse=True) # sort by 'commonality' score
            self.pinyin = pinyin

    def __lt__(self, other):
        return self.char < other.char

# gather and sort all honzi and their variants' jyutping from charlist.csv and yitizi
lines = []
with open('charlist.csv', "r") as file:
    lines = file.readlines()
honzis = []
charsSoFar = []
for i in range(1, len(lines)):
    line_split = lines[i].split(',', 1)
    char = line_split[0]
    jyutpings = re.findall('""([^"]*)"":\s+(\d+)', line_split[1])
    if (char not in charsSoFar): # prevent duplicates
        honzis.append(Honzi(char, jyutpings, pinyin.get(char)))
        charsSoFar.append(char)
    # Append character variants
    variants = yitizi.get(char) 
    for variant in variants:
        if (variant not in charsSoFar): # prevent duplicates
            honzis.append(Honzi(variant, jyutpings, pinyin.get(char)))
            charsSoFar.append(variant)
honzis.sort(key=lambda x: x.char, reverse=False) # sort by unicode


# Generate jyutping.h or constants.rs with [honzis]
out = \
"""
/*********************************************
*
*\tAUTOGENERATED BY generate_header.py
*\tJYUTPING FROM charlist.csv
*\tCHARACTER VARIANTS DERIVED FROM yitizi
*
**********************************************/

"""
out += "pub const DICT_LENGTH: usize = " + str(len(honzis)) + ";\n"
out += "pub const DICT: [[&str; 3];" + " DICT_LENGTH" + "] =\n[\n"
for honzi in honzis:
    out += "\t[ "
    out += "\"" + honzi.char + "\"" + ", "
    out += "\"" + ":".join([jyutping[0] for jyutping in honzi.jyutpings]) + "\"" + ", "
    out += "\"" + honzi.pinyin + "\""
    out += "],\n"
out = out[0:len(out) - 2] + "\n" # remove extra ',' and replace newline
out += "];"
with open('constants.rs', "w") as file:
    file.write(out)